"""CircuitAgent Public Client & Specification Package."""

from .chip_rules import (
    ChipPinoutRule,
    apply_chip_pinout,
    get_chip_rule,
    list_supported_chips,
    register_chip_rule,
    validate_pin_allocation,
)
from .circuit_blocks import (
    CircuitBlock,
    CircuitComponent,
    block_battery_tp4056,
    block_button,
    block_buzzer,
    block_can_transceiver,
    block_crystal_clock,
    block_esd_can_tvs,
    block_esd_rs485_tvs,
    block_esd_usb_tvs,
    block_ethernet_phy_w5500,
    block_fiducial_marks,
    block_i2c_header,
    block_isolated_adc_ina219,
    block_led,
    block_motor_driver_drv8825,
    block_optocoupler_isolated_io,
    block_power_ldo_3v3,
    block_power_pi_filter,
    block_reverse_polarity_protection,
    block_rs485_transceiver,
    block_sensor_aht20,
    block_sensor_mpu6050,
    block_testpoint_matrix,
    block_usb_c_power,
    block_watchdog_supervisor,
)
from .export_engine import (
    export_jlcpcb_bom,
    export_jlcpcb_cpl,
    export_kicad_netlist,
    render_ascii_topology,
)
from .industrial_dfx import (
    IPC2221_CLEARANCES,
    DFXViolation,
    IndustrialDFXReport,
    TraceCurrentResult,
    audit_industrial_dfx,
    calculate_ipc2152,
    get_ipc2221_clearance,
    solve_trace_width_ipc2152,
)
from .lcsc_client import search_lcsc_parts
from .parametric_equations import (
    DividerResult,
    I2CPullUpResult,
    LDOThermalResult,
    RCFilterResult,
    calculate_i2c_pullup,
    calculate_ldo_thermal,
    calculate_rc_filter,
    generate_standard_series,
    snap_to_e_series,
    solve_resistor_divider,
)
from .synthesizer import synthesize_from_prompt

__version__ = "0.2.2"

__all__ = [
    "IPC2221_CLEARANCES",
    "ChipPinoutRule",
    "CircuitBlock",
    "CircuitComponent",
    "DFXViolation",
    "DividerResult",
    "I2CPullUpResult",
    "IndustrialDFXReport",
    "LDOThermalResult",
    "RCFilterResult",
    "TraceCurrentResult",
    "__version__",
    "apply_chip_pinout",
    "audit_industrial_dfx",
    "block_battery_tp4056",
    "block_button",
    "block_buzzer",
    "block_can_transceiver",
    "block_crystal_clock",
    "block_esd_can_tvs",
    "block_esd_rs485_tvs",
    "block_esd_usb_tvs",
    "block_ethernet_phy_w5500",
    "block_fiducial_marks",
    "block_i2c_header",
    "block_isolated_adc_ina219",
    "block_led",
    "block_motor_driver_drv8825",
    "block_optocoupler_isolated_io",
    "block_power_ldo_3v3",
    "block_power_pi_filter",
    "block_reverse_polarity_protection",
    "block_rs485_transceiver",
    "block_sensor_aht20",
    "block_sensor_mpu6050",
    "block_testpoint_matrix",
    "block_usb_c_power",
    "block_watchdog_supervisor",
    "calculate_i2c_pullup",
    "calculate_ipc2152",
    "calculate_ldo_thermal",
    "calculate_rc_filter",
    "export_jlcpcb_bom",
    "export_jlcpcb_cpl",
    "export_kicad_netlist",
    "generate_standard_series",
    "get_chip_rule",
    "get_ipc2221_clearance",
    "list_supported_chips",
    "register_chip_rule",
    "render_ascii_topology",
    "search_lcsc_parts",
    "snap_to_e_series",
    "solve_resistor_divider",
    "solve_trace_width_ipc2152",
    "synthesize_from_prompt",
    "validate_pin_allocation",
]
